version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app/backend
    command: /bin/sh -c "cargo watch -s 'cargo run'"
