version: "3.8"

services:
  backend-development:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app/backend
    command: /bin/sh -c "cargo watch -s 'cargo run'"

  mysql-development:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD="root-password"
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
