version: "3.8"

services:
  backend-development:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-development
    env_file:
      - ./.env.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app/backend
    command: /bin/sh -c "cargo watch -s 'cargo run --bin run_server'"

  mysql-development:
    image: mysql:8.3.0
    container_name: mysql-development
    env_file:
      - ./.env.dev
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
