openapi: 3.0.3
info:
  title: "weekend-vocabulary"
  description: |
    This is a server for english vocabulary.
  version: "1.0.0"
paths:
  /get/recent:
    get:
      description: "Return recently regisitered vocabulary"
      responses:
        "200":
          description: "ok response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecentlyVocabularyResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /get/all:
    get:
      description: "Return all regisitered vocabulary list"
      responses:
        "200":
          description: "ok response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllVocabularyResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /register:
    put:
      description: "Regisiter vocabulary"
      requestBody:
        description: "vocabulary"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterVocabularyRequestBody"
      responses:
        "200":
          description: "ok response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterVocabularyOkResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /update:
    put:
      description: "Update vocabulary"
      requestBody:
        description: "vocabulary"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateVocabularyRequestBody"
      responses:
        "200":
          description: "ok response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateVocabularyOkResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    NotFound:
      description: "The specified resource was not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Vocabulary:
      properties:
        id:
          type: integer
        part_of_speech:
          type: string
          enum:
            [
              noun,
              pronoun,
              adjective,
              verb,
              adverb,
              preposition,
              conjunction,
              interjection,
            ]
        spelling:
          type: string
        meaning:
          type: string
      required:
        - part_of_speech
        - spelling
        - meaning
    RecentlyVocabularyResponse:
      properties:
        vocabulary:
          $ref: "#/components/schemas/Vocabulary"
      required:
        - vocabulary
    AllVocabularyResponse:
      properties:
        vocabulary_list:
          type: array
          items:
            $ref: "#/components/schemas/Vocabulary"
        total_count:
          type: integer
      required:
        - vocabulary_list
        - total_count
    RegisterVocabularyInput:
      properties:
        part_of_speech:
          type: string
          enum:
            [
              noun,
              pronoun,
              adjective,
              verb,
              adverb,
              preposition,
              conjunction,
              interjection,
            ]
        spelling:
          type: string
        meaning:
          type: string
      required:
        - part_of_speech
        - spelling
        - meaning
    RegisterVocabularyRequestBody:
      properties:
        vocabulary:
          $ref: "#/components/schemas/RegisterVocabularyInput"
      required:
        - vocabulary
    RegisterVocabularyOkResponse:
      properties:
        message:
          type: string
      required:
        - message
    UpdateVocabularyInput:
      properties:
        id:
          type: integer
        part_of_speech:
          type: string
          enum:
            [
              noun,
              pronoun,
              adjective,
              verb,
              adverb,
              preposition,
              conjunction,
              interjection,
            ]
        spelling:
          type: string
        meaning:
          type: string
      required:
        - id
        - part_of_speech
        - spelling
        - meaning
    UpdateVocabularyRequestBody:
      properties:
        vocabulary:
          $ref: "#/components/schemas/UpdateVocabularyInput"
      required:
        - vocabulary
    UpdateVocabularyOkResponse:
      properties:
        message:
          type: string
      required:
        - message
    Error:
      type: object
      properties:
        message:
          type: string
