openapi: 3.0.3
info:
  title: "weekend-vocabulary"
  description: |
    This API allows ...
  version: "1.0.0"
paths:
  /get/recent:
    get:
      responses:
        "200":
          description: "Get recently regisitered vocabulary"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecentlyVocabularyResponse"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Error"
components:
  schemas:
    Vocabulary:
      properties:
        id:
          type: integer
        part_of_speech:
          type: string
        spelling:
          type: string
        meaning:
          type: string
      required:
        - id
        - part_of_speech
        - spelling
        - meaning
    RecentlyVocabularyResponse:
      properties:
        vocabulary:
          $ref: "#/components/schemas/Vocabulary"
      required:
        - vocabulary
