openapi: 3.0.3
info:
  title: "weekend-vocabulary"
  description: |
    This API allows ...
  version: "1.0.0"
paths:
  /get/recent:
    get:
      responses:
        "200":
          description: "Get recently regisitered vocabulary"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecentlyVocabularyResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    NotFound:
      description: "The specified resource was not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Vocabulary:
      properties:
        id:
          type: integer
        part_of_speech:
          type: string
          enum:
            [
              noun,
              pronoun,
              adjective,
              verb,
              adverb,
              preposition,
              conjunction,
              interjection,
            ]
        spelling:
          type: string
        meaning:
          type: string
      required:
        - id
        - part_of_speech
        - spelling
        - meaning
    RecentlyVocabularyResponse:
      properties:
        vocabulary:
          $ref: "#/components/schemas/Vocabulary"
      required:
        - vocabulary
    Error:
      type: object
      properties:
        message:
          type: string
